/*
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the License). You may not use this file except in
 * compliance with the License.
 *
 * You can obtain a copy of the License at http://www.netbeans.org/cddl.html
 * or http://www.netbeans.org/cddl.txt.
 *
 * When distributing Covered Code, include this CDDL Header Notice in each file
 * and include the License file at http://www.netbeans.org/cddl.txt.
 * If applicable, add the following below the CDDL Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * The Original Software is NetBeans. The Initial Developer of the Original
 * Software is Sun Microsystems, Inc. Portions Copyright 1997-2007 Sun
 * Microsystems, Inc. All Rights Reserved.
 */
package org.netbeans.modules.gwt4nb.services;

import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.netbeans.modules.gwt4nb.GWTProjectInfo;

/**
 *
 * @author  Tomasz.Slota@Sun.COM
 */
public class NewServicePanelVisual extends javax.swing.JPanel {
    private String clientPckg;
    private String serverPckg;
    private NewServicePanel controller;
    private String gwtOutputDir;
    
    /** Creates new form NewServicePanelVisual */
    public NewServicePanelVisual(NewServicePanel controller) {
        this.controller = controller;
        initComponents();
        
        // cache these expensive to calc values
        clientPckg = GWTProjectInfo.getClientPackage(controller.getProject());
        serverPckg = GWTProjectInfo.getServerPackage(controller.getProject());
        gwtOutputDir = GWTProjectInfo.getGWTOutputDir(controller.getProject());
        
        txtServiceName.getDocument().addDocumentListener(new ChangeListener());
        txtSubpackage.getDocument().addDocumentListener(new ChangeListener());
        
        SwingUtilities.invokeLater(new Runnable(){ // Avoid endless loop
            public void run() {
                update();
            }
        });
    }
    
    public String getServiceName(){
        return txtServiceName.getText();
    }
    
    public String getServiceSubpackage(){
        return txtSubpackage.getText();
    }
    
    public String getServletMapping(){
        return txtServletMapping.getText();
    }
    
    public boolean createUsageExample(){
        return chkCreateExample.isSelected();
    }
    
    private void update(){
        String serviceName = txtServiceName.getText();
        String subpackage = txtSubpackage.getText();
        if(subpackage != null && !subpackage.equals("")){
            subpackage += ".";
        }
        
        String local = clientPckg + "." + subpackage + serviceName;
        String remote = serverPckg + "." + subpackage + serviceName + "Impl";
        String async = clientPckg + "." + subpackage + serviceName + "Async";
        txtLocalIFace.setText(local);
        txtAsyncIFace.setText(async);
        txtRemoteImpl.setText(remote);
        
        StringBuilder urlPattern = new StringBuilder();
        
        if(txtSubpackage.getText().length()>0){
            urlPattern.append(txtSubpackage.getText().toLowerCase()+"/");
        }
        urlPattern.append(txtServiceName.getText().toLowerCase());
        
        txtServletMapping.setText(urlPattern.toString());
        
        controller.fireChangeEvent();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblServiceName = new javax.swing.JLabel();
        txtServiceName = new javax.swing.JTextField();
        lblLocalIFace = new javax.swing.JLabel();
        lblRemoteImpl = new javax.swing.JLabel();
        lblAsyncIFace = new javax.swing.JLabel();
        txtAsyncIFace = new javax.swing.JTextField();
        txtLocalIFace = new javax.swing.JTextField();
        txtRemoteImpl = new javax.swing.JTextField();
        lblServletMapping = new javax.swing.JLabel();
        txtServletMapping = new javax.swing.JTextField();
        chkCreateExample = new javax.swing.JCheckBox();
        lblSubpackage = new javax.swing.JLabel();
        txtSubpackage = new javax.swing.JTextField();

        lblServiceName.setText(org.openide.util.NbBundle.getMessage(NewServicePanelVisual.class, "NewServicePanelVisual.lblServiceName.text"));

        txtServiceName.setText(org.openide.util.NbBundle.getMessage(NewServicePanelVisual.class, "NewServicePanelVisual.txtServiceName.text"));

        lblLocalIFace.setText(org.openide.util.NbBundle.getMessage(NewServicePanelVisual.class, "NewServicePanelVisual.lblLocalIFace.text"));

        lblRemoteImpl.setText(org.openide.util.NbBundle.getMessage(NewServicePanelVisual.class, "NewServicePanelVisual.lblRemoteImpl.text"));

        lblAsyncIFace.setText(org.openide.util.NbBundle.getMessage(NewServicePanelVisual.class, "NewServicePanelVisual.lblAsyncIFace.text"));

        txtAsyncIFace.setEditable(false);
        txtAsyncIFace.setText(org.openide.util.NbBundle.getMessage(NewServicePanelVisual.class, "NewServicePanelVisual.txtAsyncIFace.text"));

        txtLocalIFace.setEditable(false);
        txtLocalIFace.setText(org.openide.util.NbBundle.getMessage(NewServicePanelVisual.class, "NewServicePanelVisual.txtLocalIFace.text"));

        txtRemoteImpl.setEditable(false);
        txtRemoteImpl.setText(org.openide.util.NbBundle.getMessage(NewServicePanelVisual.class, "NewServicePanelVisual.txtRemoteImpl.text"));

        lblServletMapping.setText(org.openide.util.NbBundle.getMessage(NewServicePanelVisual.class, "NewServicePanelVisual.lblServletMapping.text"));

        txtServletMapping.setEditable(false);
        txtServletMapping.setText(org.openide.util.NbBundle.getMessage(NewServicePanelVisual.class, "NewServicePanelVisual.txtServletMapping.text"));

        chkCreateExample.setSelected(true);
        chkCreateExample.setText(org.openide.util.NbBundle.getMessage(NewServicePanelVisual.class, "NewServicePanelVisual.chkCreateExample.text"));
        chkCreateExample.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkCreateExample.setMargin(new java.awt.Insets(0, 0, 0, 0));

        lblSubpackage.setText("Subpackage:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblServiceName)
                            .add(lblSubpackage))
                        .add(71, 71, 71)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, txtServiceName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .add(txtSubpackage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)))
                    .add(chkCreateExample)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblLocalIFace)
                            .add(lblAsyncIFace)
                            .add(lblRemoteImpl)
                            .add(lblServletMapping))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, txtServletMapping, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .add(txtAsyncIFace, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtRemoteImpl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, txtLocalIFace, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblServiceName)
                    .add(txtServiceName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(5, 5, 5)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblSubpackage)
                    .add(txtSubpackage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(txtServletMapping, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblServletMapping))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblLocalIFace)
                    .add(txtLocalIFace, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtAsyncIFace, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblAsyncIFace))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblRemoteImpl)
                    .add(txtRemoteImpl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(13, 13, 13)
                .add(chkCreateExample)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkCreateExample;
    private javax.swing.JLabel lblAsyncIFace;
    private javax.swing.JLabel lblLocalIFace;
    private javax.swing.JLabel lblRemoteImpl;
    private javax.swing.JLabel lblServiceName;
    private javax.swing.JLabel lblServletMapping;
    private javax.swing.JLabel lblSubpackage;
    private javax.swing.JTextField txtAsyncIFace;
    private javax.swing.JTextField txtLocalIFace;
    private javax.swing.JTextField txtRemoteImpl;
    private javax.swing.JTextField txtServiceName;
    private javax.swing.JTextField txtServletMapping;
    private javax.swing.JTextField txtSubpackage;
    // End of variables declaration//GEN-END:variables
    
    private class ChangeListener implements DocumentListener{
        public void insertUpdate(DocumentEvent arg0) {
            update();
        }
        
        public void removeUpdate(DocumentEvent arg0) {
            update();
        }
        
        public void changedUpdate(DocumentEvent arg0) {
            update();
        }
    }
}
